import { IMAGE_PATH } from "../../constants/images";

export const fakeProducts = [
  {
    image: IMAGE_PATH.FRAME1,
    title: "T-shirt with Tape Details",
    stars: 4.5,
    price: 120,
  },
  {
    image: IMAGE_PATH.FRAME2,
    title: "Skinny Fit Jeans",
    stars: 3.5,
    price: 260,
    discount: 20,
  },
  {
    image: IMAGE_PATH.FRAME3,
    title: "Checkered Shirt",
    stars: 4.5,
    price: 180,
  },
  {
    image: IMAGE_PATH.FRAME4,
    title: "Sleeve Stiped T-shirt",
    stars: 4.5,
    price: 160,
    discount: 30,
  },
  {
    image: IMAGE_PATH.FRAME5,
    title: "Vertical Striped Shirt",
    stars: 5,
    price: 232,
    discount: 20,
  },
  {
    image: IMAGE_PATH.FRAME6,
    title: "Courage Graphic T-shirt",
    stars: 4,
    price: 145,
  },
  {
    image: IMAGE_PATH.FRAME7,
    title: "Loose Fit Bermuda Shorts",
    stars: 3,
    price: 80,
  },
  {
    image: IMAGE_PATH.FRAME8,
    title: "Faded Skinny Jeans",
    stars: 4.5,
    price: 210,
  },
  {
    image: IMAGE_PATH.PRODUCT1,
    title: "Polo with Contrast Trims",
    stars: 4,
    price: 242,
    discount: 20,
  },
  {
    image: IMAGE_PATH.PRODUCT2,
    title: "Gradient Graphic T-shirt",
    stars: 3.5,
    price: 145,
  },
  {
    image: IMAGE_PATH.PRODUCT3,
    title: "Polo with Tipping Details",
    stars: 4.5,
    price: 180,
  },
  {
    image: IMAGE_PATH.PRODUCT4,
    title: "Black Striped T-shirt",
    stars: 5,
    price: 150,
    discount: 30,
  },
  {
    image: IMAGE_PATH.FRAME1,
    title: "T-shirt with Tape Details",
    stars: 4.5,
    price: 120,
  },
  {
    image: IMAGE_PATH.FRAME2,
    title: "Skinny Fit Jeans",
    stars: 3.5,
    price: 260,
    discount: 20,
  },
  {
    image: IMAGE_PATH.FRAME3,
    title: "Checkered Shirt",
    stars: 4.5,
    price: 180,
  },
  {
    image: IMAGE_PATH.FRAME4,
    title: "Sleeve Stiped T-shirt",
    stars: 4.5,
    price: 160,
    discount: 30,
  },
  {
    image: IMAGE_PATH.FRAME5,
    title: "Vertical Striped Shirt",
    stars: 5,
    price: 232,
    discount: 20,
  },
  {
    image: IMAGE_PATH.FRAME6,
    title: "Courage Graphic T-shirt",
    stars: 4,
    price: 145,
  },
  {
    image: IMAGE_PATH.FRAME7,
    title: "Loose Fit Bermuda Shorts",
    stars: 3,
    price: 80,
  },
  {
    image: IMAGE_PATH.FRAME8,
    title: "Faded Skinny Jeans",
    stars: 4.5,
    price: 210,
  },
  {
    image: IMAGE_PATH.PRODUCT1,
    title: "Polo with Contrast Trims",
    stars: 4,
    price: 242,
    discount: 20,
  },
  {
    image: IMAGE_PATH.PRODUCT2,
    title: "Gradient Graphic T-shirt",
    stars: 3.5,
    price: 145,
  },
  {
    image: IMAGE_PATH.PRODUCT3,
    title: "Polo with Tipping Details",
    stars: 4.5,
    price: 180,
  },
  {
    image: IMAGE_PATH.PRODUCT4,
    title: "Black Striped T-shirt",
    stars: 5,
    price: 150,
    discount: 30,
  },
];